lhsmtool_cmd: remove include to lustre_user.h
Including that header has been deprecated in recent versions of lustre (LU-6401)
In file included from lhsmtool_cmd.c:76:0:
/usr/include/lustre/lustre_user.h:45:2: error: #warning "Including lustre_user.h
is deprecated. Include linux/lustre/lustre_user.h directly." [-Werror=cpp]

It appears that the header is not needed anyway

Change-Id: I0c78dcca756e1f34fad2c3cbafc1438d3cbf1795